# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tsaura-n <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/29 23:53:32 by tsaura-n          #+#    #+#              #
#    Updated: 2019/09/18 21:37:00 by tsaura-n         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all : run

run :
	@echo wrong\n
	../fillit noNL.txt
	../fillit onlyNL.txt
	../fillit twoNL.txt
	../fillit falsetet.txt
	../fillit falsetet2.txt
	../fillit 3dotline.txt
	../fillit 3linesbloc.txt
	../fillit emptytet.txt
	@echo right\n
	../fillit sqanswer.txt
	../fillit alldifftet.txt
	../fillit cubes.txt
	../fillit lines.txt

