# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tsaura-n <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/29 23:53:32 by tsaura-n          #+#    #+#              #
#    Updated: 2019/09/18 21:37:00 by tsaura-n         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all : run

run :
	@echo wrong
	../fillit 
	../fillit noNL.txt onlyNL.txt
	../fillit noNL.txt 
	../fillit onlyNL.txt
	../fillit twoNL.txt
	../fillit falsetet.txt
	../fillit falsetet2.txt
	../fillit 3dotline.txt
	../fillit 3linesbloc.txt
	../fillit emptytet.txt
	../fillit 27tet.txt
	@echo right
	../fillit onetet.txt
	../fillit tetaa.txt
	../fillit tetab.txt
	../fillit tetac.txt
	../fillit tetad.txt
	../fillit tetae.txt
	../fillit tetag.txt
	../fillit tetah.txt
	../fillit tetai.txt
	../fillit tetaj.txt
	../fillit tetak.txt
	../fillit tetal.txt
	../fillit tetam.txt
	../fillit tetan.txt
	../fillit tetao.txt
	../fillit tetap.txt
	../fillit tetaq.txt
	../fillit tetar.txt
	../fillit tetas.txt
	../fillit tetat.txt
	../fillit tetau.txt
	../fillit tetav.txt
	../fillit tetaw.txt
	../fillit tetax.txt
	time ../fillit sqanswer.txt
	time ../fillit alldifftet.txt
	time ../fillit cubes.txt
	time ../fillit lines.txt
