# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tsaura-n <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/29 23:53:32 by tsaura-n          #+#    #+#              #
#    Updated: 2019/08/30 01:12:09 by tsaura-n         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all : run

run :
	@echo wrong \

	@echo | ../fillit test01.txt \

	@echo | ../fillit test02.txt \

	@echo | ../fillit test03.txt \

	@echo | ../fillit test04.txt \

	@echo | ../fillit test05.txt \

	@echo | ../fillit test06.txt \

	@echo | ../fillit test07.txt \

	@echo | ../fillit test08.txt \

	@echo right \

	@echo | ../fillit testr1.txt \

	@echo | ../fillit testr2.txt

